
// ## category response
export const ERROR_CREATING_CATEGORY = 'ERROR_CREATING_CATEGORY'
export const ERROR_UPDATING_CATEGORY = 'ERROR_UPDATING_CATEGORY'
export const ERROR_FETCHING_CATEGORY = 'ERROR_FETCHING_CATEGORY'
export const INVALID_CATEGORY_TYPE_FOR = 'INVALID_CATEGORY_TYPE_FOR'
export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND'

// ## product response
export const ERROR_CREATING_PRODUCT = 'ERROR_CREATING_PRODUCT'
export const ERROR_UPDATING_PRODUCT = 'ERROR_UPDATING_PRODUCT'
export const ERROR_FETCHING_PRODUCT = 'ERROR_FETCHING_PRODUCT'
export const SAME_PRODUCT_ON_A_CUSTOMER = 'SAME_PRODUCT_ON_A_CUSTOMER'
export const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND'
export const NOT_OWNER_OF_THE_PRODUCT = 'NOT_OWNER_OF_THE_PRODUCT'

// ## seller response
export const SELLER_NOT_FOUND = 'SELLER_NOT_FOUND'

// ## Adding to favorite
export const PBM_IN_ADDING_FAVORITE = 'PBM_IN_ADDING_FAVORITE'


// ## Error response
export const INVALID_PARAMS = 'INVALID_PARAMS'