
// ## category response
export const ERROR_CREATING_CATEGORY = 'ERROR_CREATING_CATEGORY'
export const ERROR_UPDATING_CATEGORY = 'ERROR_UPDATING_CATEGORY'
export const ERROR_FETCHING_CATEGORY = 'ERROR_FETCHING_CATEGORY'
export const INVALID_CATEGORY_TYPE_FOR = 'INVALID_CATEGORY_TYPE_FOR'
export const INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN'



// ## Error response
export const INVALID_PARAMS = 'INVALID_PARAMS'